### ISSUE TITLE
为什么不能输入密令呢

### ISSUE THREAD

**Issue by wannaliang** [techstreat/SSH-Android#1]
为什么不能输入密令呢

**Comment by ekanshsinghal** [comment]
Can you be more specific?

**Comment by wannaliang** [comment]
Hello, that is, after the soft keyboard pops up, why does it not have any effect after entering the content, just connect successfully.

**Comment by ekanshsinghal** [comment]
If you are referring to the password, that’s how Linux terminal works. Password does get entered but it wouldn’t display anything. That’s not an issue in this app.

**Comment by wannaliang** [comment]
No, I'm not referring to the password. I've been landing, and then from the main interface to the terminal interface (the black background interface) that has been landed. I type the password at the interface to control the terminal. There is no effect on this interface, that is, the input button does not play any role. Is this procedure like this? Is there any way to adjust it? Thank you

**Comment by ekanshsinghal** [comment]
Once you are at the terminal interface(black background) you don’t need to type the password again. Its logged in, just start using it like normal terminal. 
Adjusting it would require to looking to Jsch library I guess.

**Comment by wannaliang** [comment]
But after entering the black terminal, it is impossible to do any operation and can not input any Ren Rong. Is there any way to solve this problem?

**Comment by wannaliang** [comment]
Sorry,The input is wrong, it's the content

**Comment by ekanshsinghal** [comment]
I guess, u are having an issue in connecting or permissions. Because the way app is supposed to work is as soon as you land on terminal screen, normal terminal commands work.

**Comment by wannaliang** [comment]
After the successful landing, the normal terminal command work, but can not enter any content on the terminal command to operate, now can not find any reason, thank you for your answer.

**Comment by ekanshsinghal** [comment]
What do you mean by content. Example?

**Comment by wannaliang** [comment]
In simple terms, the keyboard is not used.

**Comment by ekanshsinghal** [comment]
It works for me. Are you using Chinese keyboard or encoding maybe different. 

I updated the repo 2 yrs ago last, maybe some code has become obsolete. Sorry for the trouble ?

**Comment by wannaliang** [comment]
OK, thank you very much.
